name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/bitgamergws1/music@main/your-music-file.mp3"
